apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: opensearch
      version: 2.32.0  # Use latest version
      sourceRef:
        kind: HelmRepository
        name: opensearch
  values:
    replicas: 1
    singleNode: true
    persistence:
      enabled: false
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        value: "Omkran_ommkwn_2001"  # Set a strong password
    nodeSelector:
      kubernetes.io/hostname: minikube  # Run on Minikube node
