apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: flux-system  # Add this line
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube  # Ensures it runs on Minikube node
      containers:
      - name: my-app
        image: ok:1.2.3
        ports:
        - containerPort: 80

