apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: flux-system  # Add this line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app-image:latest
