apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opensearch
  namespace: flux-system
spec:
  interval: 5m
  url: https://opensearch-project.github.io/helm-charts/  # OpenSearch Helm repo
